USE [master]
GO

/****** Object:  Database [ALFMovers]    Script Date: 04/10/2017 4:31:53 PM ******/
CREATE DATABASE [ALFMovers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ALFMovers', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ALFMovers.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ALFMovers_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ALFMovers_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ALFMovers] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ALFMovers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ALFMovers] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ALFMovers] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ALFMovers] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ALFMovers] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ALFMovers] SET ARITHABORT OFF 
GO

ALTER DATABASE [ALFMovers] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ALFMovers] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ALFMovers] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ALFMovers] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ALFMovers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ALFMovers] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ALFMovers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ALFMovers] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ALFMovers] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ALFMovers] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ALFMovers] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ALFMovers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ALFMovers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ALFMovers] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ALFMovers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ALFMovers] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ALFMovers] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ALFMovers] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ALFMovers] SET RECOVERY FULL 
GO

ALTER DATABASE [ALFMovers] SET  MULTI_USER 
GO

ALTER DATABASE [ALFMovers] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ALFMovers] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ALFMovers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ALFMovers] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ALFMovers] SET  READ_WRITE 
GO

