//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALFMovers.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ALFMoversEntities : DbContext
    {
        public ALFMoversEntities()
            : base("name=ALFMoversEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Truck> Trucks { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<TransEmp> TransEmps { get; set; }
        public DbSet<TransTruck> TransTrucks { get; set; }
    }
}
