//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALFMovers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransEmps = new HashSet<TransEmp>();
            this.TransTrucks = new HashSet<TransTruck>();
        }
    
        public int TransID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<int> CustID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<TransEmp> TransEmps { get; set; }
        public virtual ICollection<TransTruck> TransTrucks { get; set; }
    }
}
